# version: '3'
# services:
#   nginx:
#     image: nginx:latest  # Use the official NGINX image
#     container_name: nginx-http  # Name the container
#     ports:
#       - "80:80"  # Map port 80 on the host to port 80 in the container
#     restart: always  # Restart container if it crashes
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-http
    ports:
      - "80:80"  # Map port 80 for NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Custom NGINX configuration
    depends_on:
      - wordpress  # Ensure WordPress is ready before starting NGINX
    restart: always

  wordpress:
    image: wordpress:php8.0-fpm  # WordPress with php-fpm
    container_name: wordpress-fpm
    environment:
      WORDPRESS_DB_HOST: db  # Database host (we'll add a database later)
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - ./wordpress:/var/www/html  # Mount WordPress files for persistence
    restart: always
